name: Sanity test of action

on:
  push:
  pull_request:

jobs:
  test-action:
    name: Sanity test of action
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./
        with:
          coverage-file: "src/__tests__/coverage.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
